defmodule Druzhok.Runtime.Hermes do
  @moduledoc """
  Runtime adapter for the Hermes agent (v4/hermes-agent).

  One container per bot. `HERMES_HOME=/opt/data` points at the tenant's data
  root on the host. All LLM traffic goes through druzhok's Elixir proxy via
  `OPENAI_BASE_URL` + `OPENAI_API_KEY`; hermes flips its inference provider
  to `"custom"` automatically when `OPENAI_BASE_URL` is set
  (see hermes_cli/main.py:915).

  The allowlist is env-var driven: druzhok writes `TELEGRAM_ALLOWED_USERS`
  at each container start from `instance.owner_telegram_id +
  instance.allowed_telegram_ids`. Hermes's own pairing store under
  `/opt/data/platforms/pairing/telegram-approved.json` is left for the bot
  to manage — we read it for the dashboard but don't write to it.
  """

  @behaviour Druzhok.Runtime

  alias Druzhok.Instance

  @data_mount "/opt/data"
  @default_model "anthropic/claude-opus-4.6"

  @impl true
  def docker_image, do: System.get_env("HERMES_IMAGE") || "hermes:latest"

  @impl true
  def gateway_command, do: ["gateway", "run"]

  @impl true
  def data_mount_path, do: @data_mount

  @impl true
  def file_browser_root(instance) do
    # Hermes writes at the mount root (cron/, sessions/, memories/, workspace/, ...).
    # Show the whole /opt/data equivalent to the operator, not just workspace/.
    case Map.get(instance, :workspace) do
      nil -> ""
      ws -> Path.dirname(ws)
    end
  end

  @impl true
  def env_vars(instance) do
    # base_env/1 already provides OPENAI_BASE_URL, OPENAI_API_KEY, TZ —
    # only add hermes-specific keys here.
    #
    # HOME points at a writable directory on the mounted data root. Without
    # it, hermes running as --user 1000:1000 hits `Path.home() == /` and
    # fails to mkdir `/.local` on boot (no /etc/passwd entry for uid 1000).
    # The hermes entrypoint creates `$HERMES_HOME/home` for exactly this
    # purpose — per-profile HOME for subprocesses (git, ssh, npm, …).
    #
    # STT_OPENAI_BASE_URL routes voice transcription through the druzhok
    # proxy's /v1/audio/transcriptions endpoint instead of api.openai.com.
    # The provider choice (openai vs local/faster-whisper) lives in
    # config.yaml's `stt:` section — see build_config_yaml/1.
    tenant_key = Map.get(instance, :tenant_key, "") || ""
    model = Map.get(instance, :model) || @default_model
    proxy_url = proxy_url()

    %{
      "HERMES_HOME" => @data_mount,
      "HERMES_QUIET" => "0",
      "HOME" => @data_mount <> "/home",
      "TELEGRAM_BOT_TOKEN" => Map.get(instance, :telegram_token, "") || "",
      "TELEGRAM_ALLOWED_USERS" => build_allowlist(instance),
      "HERMES_INFERENCE_PROVIDER" => "custom",
      "OPENROUTER_API_KEY" => tenant_key,
      "HERMES_MODEL" => model,
      "STT_OPENAI_BASE_URL" => proxy_url
    }
  end

  @impl true
  def workspace_files(instance) do
    # :create_only — write on fresh data root only. Hermes persists runtime
    # state (telegram thread IDs, etc.) back into config.yaml at runtime, so
    # we must never overwrite it on restart.
    [{"config.yaml", build_config_yaml(instance), :create_only}]
  end

  @impl true
  def post_start(_instance), do: :ok

  @impl true
  def parse_log_rejection(_line), do: :ignore

  @impl true
  def clear_sessions(data_root) do
    data_root
    |> Path.join("sessions")
    |> File.rm_rf!()

    :ok
  end

  @impl true
  def read_allowed_users(data_root) do
    path = Path.join([data_root, "platforms", "pairing", "telegram-approved.json"])

    with {:ok, body} <- File.read(path),
         {:ok, map} when is_map(map) <- Jason.decode(body) do
      Map.keys(map)
    else
      _ -> []
    end
  end

  @impl true
  def add_allowed_user(_data_root, _user_id), do: :ok

  @impl true
  def remove_allowed_user(_data_root, _user_id), do: :ok

  @impl true
  def supports_feature?(:db_allowlist), do: true
  def supports_feature?(:pairing_code_approval), do: true
  def supports_feature?(_), do: false

  # --- Helpers ---

  defp build_allowlist(instance) do
    owner =
      case Map.get(instance, :owner_telegram_id) do
        nil -> []
        "" -> []
        id -> [to_string(id)]
      end

    extra = Instance.get_allowed_ids(instance)

    (owner ++ extra)
    |> Enum.reject(&(&1 in [nil, ""]))
    |> Enum.uniq()
    |> Enum.join(",")
  end

  defp build_config_yaml(instance) do
    model = Map.get(instance, :model) || @default_model

    """
    # Generated by druzhok on first boot. Feel free to edit — druzhok will
    # NOT overwrite this file on restart (it only seeds it once).
    model:
      default: "#{model}"
      provider: "custom"
      base_url: "#{proxy_url()}"

    platforms:
      telegram:
        enabled: true

    messaging:
      enabled_platforms:
        telegram: [hermes-telegram]

    stt:
      enabled: true
      provider: "openai"
      openai:
        model: "whisper-1"
    """
  end

  defp proxy_url do
    proxy_host = Druzhok.Runtime.proxy_host()
    proxy_port = System.get_env("LLM_PROXY_PORT") || "4000"
    "http://#{proxy_host}:#{proxy_port}/v1"
  end
end
